services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./ui:/app/ui
      - lora-data:/data
    environment:
      - HOME=/root
      - TERM=xterm
    mem_limit: 12G
    ports:
      - 8080:8080
    working_dir: "/app"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped

volumes:
  lora-data:
